local function run(msg, matches)
	if not is_momod(msg) then 
		return " Shield bot Help for mods : 😈\nPlugins : 🔻\n1. banhammer ⭕️\nHelp For Banhammer👇\n!Kick @UserName 😜\nAnd You Can do It by Replay 🙈\n!Ban @UserName 〽️\nYou Can Do It By Replay👌\n!Unban @UserName\nYou Can Do it By Replay😱\nFor Admins : 👇\n!banall @UserName or (user_id)😺\nyou Can do it By Replay 👤\n!unbanall 🆔User_Id🆔\n〰〰〰〰〰〰〰〰〰〰\n2. GroupManager :🔹\n!Creategp \"GroupName\" 🙈\nYou Can CreateGroup With this command😱\n!lock member 😋\nYou Can lock Your Group Members 🔻\n!lock bots 🔹\nNo bots can come in Your gp 🕶\n!lock name ❤️\nno one can change your gpname💍\n!setflood😃\nSet the group flood control🈹\n!settings ❌\nWatch group settings\n!owner🚫\nwatch group owner\n!setowner user_id❗️\nYou can set someone to the group owner‼️\n!modlist💯\nwatch Group mods🔆\n!lock|unlock (bots-member-photo-name-Arabic)✅️\nlock something🔰\n!unlock (bots-member-flood-photo-name-Arabic)✅\nUnlock Something🚼\n!sticker warn\nfor giving warning to somebody (when send sticker)\n!sticker kick \nfor kicking somebody (when send sticker)\n!sticker ok\nfor unlock sending sticker\n!rules 🆙 or !set rules🆗\nwatch group rules or set\n!about or !set about 🔴\n!res @username🔘\nSee UserInfo©\n!who♦️\nGet Ids Chat🔺\n!log 🎴\nget members id ♠️\n!all🔴\nthis is like stats in a file🔸\nfor getting link use :\ngetting !link 😏\ngetting link in pv !linkpv😏\nrevoke !clink😏 :)\n〰〰〰〰〰〰〰〰\nAdmins :®\n!add 😎\nYou Can add the group to moderation.json😱\n!rem😏\nYou Can Remove the group from mod.json⭕️\n!setgpowner (Gpid) user_id ⚫️\nfrom realm®®\n!addadmin 🔶\nset some one to global admin🔸\n!removeadmin🔘\nremove somone from global admin🔹\n〰〰〰〰〰〰〰〰〰〰〰\n3. Stats :©\n!stats shield (sudoers)✔️\nshows bt stats🔚\n!stats🔘\nshows group stats💲\n〰〰〰〰〰〰〰〰\n4. Feedback⚫️\n!feedback txt🔻◼️\nsend maseage to admins via bot🔈\n〰〰〰〰〰〰〰〰〰〰〰\n5. Tagall◻️\n!tagall txt🔸\nwill tag users©\n〰〰〰〰〰〰〰〰〰\n!shieldbot\nTo Know About Us\n〰〰〰〰〰〰〰〰\n🔜 more plugins \n⚠️ComingSoon... ⚠️\nour channel : ComingSoon🔋\nYou Can use both \"!\" & \"/\" for them🎧\n "
	end
	if matches[1] then
		return " Shield bot Help for mods : 😈\nPlugins : 🔻\n1. banhammer ⭕️\nHelp For Banhammer👇\n!Kick @UserName 😜\nAnd You Can do It by Replay 🙈\n!Ban @UserName 〽️\nYou Can Do It By Replay👌\n!Unban @UserName\nYou Can Do it By Replay😱\nFor Admins : 👇\n!banall @UserName or (user_id)😺\nyou Can do it By Replay 👤\n!unbanall 🆔User_Id🆔\n〰〰〰〰〰〰〰〰〰〰\n2. GroupManager :🔹\n!Creategp \"GroupName\" 🙈\nYou Can CreateGroup With this command😱\n!lock member 😋\nYou Can lock Your Group Members 🔻\n!lock bots 🔹\nNo bots can come in Your gp 🕶\n!lock name ❤️\nno one can change your gpname💍\n!setflood😃\nSet the group flood control🈹\n!settings ❌\nWatch group settings\n!owner🚫\nwatch group owner\n!setowner user_id❗️\nYou can set someone to the group owner‼️\n!modlist💯\nwatch Group mods🔆\n!lock|unlock (bots-member-photo-name-Arabic)✅️\nlock something🔰\n!unlock (bots-member-flood-photo-name-Arabic)✅\nUnlock Something🚼\n!sticker warn\nfor giving warning to somebody (when send sticker)\n!sticker kick \nfor kicking somebody (when send sticker)\n!sticker ok\nfor unlock sending sticker\n!rules 🆙 or !set rules🆗\nwatch group rules or set\n!about or !set about 🔴\n!res @username🔘\nSee UserInfo©\n!who♦️\nGet Ids Chat🔺\n!log 🎴\nget members id ♠️\n!all🔴\nthis is like stats in a file🔸\nfor getting link use :\ngetting !link 😏\ngetting link in pv !linkpv😏\nrevoke !clink😏 :)\n〰〰〰〰〰〰〰〰\nAdmins :®\n!add 😎\nYou Can add the group to moderation.json😱\n!rem😏\nYou Can Remove the group from mod.json⭕️\n!setgpowner (Gpid) user_id ⚫️\nfrom realm®®\n!addadmin 🔶\nset some one to global admin🔸\n!removeadmin🔘\nremove somone from global admin🔹\n〰〰〰〰〰〰〰〰〰〰〰\n3. Stats :©\n!stats shield (sudoers)✔️\nshows bt stats🔚\n!stats🔘\nshows group stats💲\n〰〰〰〰〰〰〰〰\n4. Feedback⚫️\n!feedback txt🔻◼️\nsend maseage to admins via bot🔈\n〰〰〰〰〰〰〰〰〰〰〰\n5. Tagall◻️\n!tagall txt🔸\nwill tag users©\n〰〰〰〰〰〰〰〰〰\n!shieldbot\nTo Know About Us\n〰〰〰〰〰〰〰〰\n🔜 more plugins \n⚠️ComingSoon... ⚠️\nour channel : ComingSoon🔋\nYou Can use both \"!\" & \"/\" for them🎧\n "
		end
	return
end


return {
  description = "",
  usage = {""},
  patterns = {
    "^[!/]([Hh]elp)";
    

  },
  run = run
}
